import { describe, it, expect, vi, beforeEach } from 'vitest';

const mockSave = vi.fn();
const mockGetNumberOfPages = vi.fn().mockReturnValue(1);
const mockSetPage = vi.fn();
const mockGetHeight = vi.fn().mockReturnValue(297);

const mockDoc = {
  save: mockSave,
  internal: {
    pageSize: {
      getWidth: vi.fn().mockReturnValue(210),
      getHeight: mockGetHeight,
    },
  },
  setFillColor: vi.fn(),
  rect: vi.fn(),
  setFont: vi.fn(),
  setFontSize: vi.fn(),
  setTextColor: vi.fn(),
  text: vi.fn(),
  setDrawColor: vi.fn(),
  line: vi.fn(),
  getNumberOfPages: mockGetNumberOfPages,
  setPage: mockSetPage,
};

const MockJsPDF = vi.fn(function (_format: string, _unit: string, _size: string) {
  return mockDoc;
});

vi.mock('jspdf', () => ({
  default: MockJsPDF,
}));

vi.mock('jspdf-autotable', () => ({
  default: vi.fn(),
}));

const { downloadPdf, downloadBookingsPdf, downloadClientsPdf, downloadFinancialPdf } =
  await import('./pdf');

describe('pdf', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetNumberOfPages.mockReturnValue(1);
  });

  describe('downloadPdf', () => {
    it('generates a pdf with rows', async () => {
      await await downloadPdf({
        title: 'Test Report',
        filename: 'test.pdf',
        columns: [
          { header: 'Name', dataKey: 'name' },
          { header: 'Value', dataKey: 'value' },
        ],
        rows: [
          { name: 'Item 1', value: 100 },
          { name: 'Item 2', value: 200 },
        ],
      });
      expect(mockSave).toHaveBeenCalledWith('test.pdf');
    });

    it('', async () => {
      await downloadPdf({
        title: 'Empty Report',
        filename: 'empty.pdf',
        columns: [{ header: 'Name', dataKey: 'name' }],
        rows: [],
      });
      expect(mockSave).toHaveBeenCalledWith('empty.pdf');
    });

    it('', async () => {
      await downloadPdf({
        title: 'Report',
        subtitle: 'Jan-Mar 2024',
        filename: 'sub.pdf',
        columns: [{ header: 'A', dataKey: 'a' }],
        rows: [{ a: 1 }],
      });
      expect(mockSave).toHaveBeenCalledWith('sub.pdf');
    });

    it('', async () => {
      await downloadPdf({
        title: 'Report',
        filename: 'brand.pdf',
        columns: [{ header: 'A', dataKey: 'a' }],
        rows: [{ a: 1 }],
        brandName: 'My Barbershop',
        brandColor: '#FF0000',
      });
      expect(mockSave).toHaveBeenCalledWith('brand.pdf');
    });

    it('', async () => {
      await downloadPdf({
        title: 'Report',
        filename: 'color.pdf',
        columns: [{ header: 'A', dataKey: 'a' }],
        rows: [{ a: 1 }],
        brandColor: 'not-a-color',
      });
      expect(mockSave).toHaveBeenCalledWith('color.pdf');
    });

    it('', async () => {
      await downloadPdf({
        title: 'Report',
        filename: 'footer.pdf',
        columns: [{ header: 'A', dataKey: 'a' }],
        rows: [{ a: 1 }],
        footerText: 'Generated by system',
      });
      expect(mockSave).toHaveBeenCalledWith('footer.pdf');
    });

    it('', async () => {
      await downloadPdf({
        title: 'Report',
        filename: 'My File (1).pdf',
        columns: [{ header: 'A', dataKey: 'a' }],
        rows: [{ a: 1 }],
      });
      expect(mockSave).toHaveBeenCalledWith('My_File__1_.pdf');
    });

    it('', async () => {
      mockGetNumberOfPages.mockReturnValue(2);
      await downloadPdf({
        title: 'Report',
        filename: 'multi.pdf',
        columns: [{ header: 'A', dataKey: 'a' }],
        rows: [{ a: 1 }],
      });
      expect(mockSetPage).toHaveBeenCalled();
    });

    it('', async () => {
      await downloadPdf({
        title: 'Report',
        filename: 'missing.pdf',
        columns: [
          { header: 'A', dataKey: 'a' },
          { header: 'B', dataKey: 'b' },
        ],
        rows: [{ a: 1 }],
      });
      expect(mockSave).toHaveBeenCalledWith('missing.pdf');
    });

    it('', async () => {
      await downloadPdf({
        title: 'Report',
        filename: 'default-brand.pdf',
        columns: [{ header: 'A', dataKey: 'a' }],
        rows: [{ a: 1 }],
      });
      expect(mockSave).toHaveBeenCalledWith('default-brand.pdf');
    });
  });

  describe('downloadBookingsPdf', () => {
    it('', async () => {
      await downloadBookingsPdf(
        [
          {
            booking_date: '2024-01-15',
            booking_time: '10:00:00',
            client_name: 'João',
            client_phone: '11999990000',
            services: 'Corte',
            total_price: 50,
            status: 'completed',
          },
        ],
        'bookings.pdf',
        'Jan 2024',
        'Black Diamond',
        '#D4AF37'
      );
      expect(mockSave).toHaveBeenCalledWith('bookings.pdf');
    });

    it('', async () => {
      await downloadBookingsPdf([], 'empty.pdf');
      expect(mockSave).toHaveBeenCalledWith('empty.pdf');
    });

    it('', async () => {
      await downloadBookingsPdf(
        [
          {
            booking_date: '',
            booking_time: '',
            client_name: '',
            client_phone: '',
            services: '',
            total_price: 0,
            status: 'unknown_status',
          },
        ],
        'fields.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('fields.pdf');
    });

    it('', async () => {
      await downloadBookingsPdf(
        [
          {
            booking_date: '2024-01-15',
            booking_time: '10:00:00',
            client_name: 'João',
            client_phone: '11999990000',
            services: 'Corte',
            total_price: 50,
            discount_amount: 10,
            status: 'confirmed',
          },
        ],
        'discount.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('discount.pdf');
    });

    it('', async () => {
      const statuses = ['pending', 'confirmed', 'completed', 'cancelled', 'unknown'] as const;
      const bookings = statuses.map((status) => ({
        booking_date: '2024-01-15',
        booking_time: '10:00:00',
        client_name: 'Client',
        client_phone: '11999990000',
        services: 'Corte',
        total_price: 50,
        status,
      }));
      await downloadBookingsPdf(bookings, 'statuses.pdf');
      expect(mockSave).toHaveBeenCalledWith('statuses.pdf');
    });

    it('', async () => {
      await downloadBookingsPdf(
        [
          {
            booking_date: '2024-01-15',
            booking_time: '10:00:00',
            client_name: 'João',
            client_phone: '11999990000',
            services: 'Corte',
            total_price: 50,
            status: 'completed',
          },
        ],
        'range.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('range.pdf');
    });

    it('', async () => {
      await downloadBookingsPdf(
        [
          {
            booking_date: '2024-01-15',
            booking_time: '10:30:45',
            client_name: 'João',
            client_phone: '11999990000',
            services: 'Corte',
            total_price: 50,
            status: 'completed',
          },
        ],
        'time.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('time.pdf');
    });
  });

  describe('downloadClientsPdf', () => {
    it('', async () => {
      await downloadClientsPdf(
        [
          {
            name: 'Maria',
            phone: '11988887777',
            visits: 5,
            last_visit: '2024-01-15',
            total_spent: 250,
            is_mensalista: false,
            is_favorite: true,
          },
        ],
        'clients.pdf',
        'My Shop',
        '#FF0000'
      );
      expect(mockSave).toHaveBeenCalledWith('clients.pdf');
    });

    it('', async () => {
      await downloadClientsPdf([], 'empty-clients.pdf');
      expect(mockSave).toHaveBeenCalledWith('empty-clients.pdf');
    });

    it('', async () => {
      await downloadClientsPdf(
        [
          {
            name: 'Mensal',
            phone: '11999990000',
            visits: 10,
            last_visit: '2024-01-15',
            total_spent: 500,
            is_mensalista: true,
            is_favorite: false,
          },
        ],
        'mensal.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('mensal.pdf');
    });

    it('', async () => {
      await downloadClientsPdf(
        [
          {
            name: 'Regular',
            phone: '11999990000',
            visits: 1,
            last_visit: '2024-01-15',
            total_spent: 50,
            is_mensalista: false,
            is_favorite: false,
          },
        ],
        'regular.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('regular.pdf');
    });

    it('', async () => {
      await downloadClientsPdf(
        [
          {
            name: '',
            phone: '',
            visits: 0,
            last_visit: '',
            total_spent: 0,
            is_mensalista: false,
            is_favorite: false,
          },
        ],
        'missing.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('missing.pdf');
    });

    it('', async () => {
      await downloadClientsPdf(
        [
          {
            name: 'Test',
            phone: '11999990000',
            visits: 1,
            last_visit: '2024-01-15',
            total_spent: 50,
            is_mensalista: false,
            is_favorite: false,
          },
        ],
        'default.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('default.pdf');
    });
  });

  describe('downloadFinancialPdf', () => {
    it('', async () => {
      await downloadFinancialPdf(
        [
          {
            month: 'Jan/2024',
            bookings: 50,
            revenue: 2500,
            cancelled: 5,
            cancelRate: '10%',
          },
        ],
        'financial.pdf',
        'My Shop',
        '#D4AF37'
      );
      expect(mockSave).toHaveBeenCalledWith('financial.pdf');
    });

    it('', async () => {
      await downloadFinancialPdf([], 'empty-fin.pdf');
      expect(mockSave).toHaveBeenCalledWith('empty-fin.pdf');
    });

    it('', async () => {
      await downloadFinancialPdf(
        [
          {
            month: '',
            bookings: 0,
            revenue: 0,
            cancelled: 0,
            cancelRate: '',
          },
        ],
        'fields-fin.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('fields-fin.pdf');
    });

    it('', async () => {
      await downloadFinancialPdf(
        [
          {
            month: 'Jan/2024',
            bookings: 10,
            revenue: 500,
            cancelled: 2,
            cancelRate: '20%',
          },
        ],
        'default-fin.pdf'
      );
      expect(mockSave).toHaveBeenCalledWith('default-fin.pdf');
    });
  });
});
