-- =========================================================================
-- BLACK DIAMOND - 012 - HARDENING DE ACESSO PÚBLICO (BOOKINGS + IS_ADMIN)
-- =========================================================================
-- Achados da auditoria 360 (2026-08-06):
--
--   🚨 1. A policy "Leitura publica agendamentos" (001/006) permitia que a
--          chave anon (pública) fizesse SELECT em TODAS as colunas de
--          bookings — incluindo `notes`, `total_price`, `discount_amount`,
--          `client_id`, `coupon_id` — de TODOS os clientes, tanto no
--          histórico completo (`status = 'completed'`) quanto nos
--          agendamentos futuros. Qualquer pessoa com a chave anon montava
--          o histórico financeiro inteiro da barbearia.
--
--          A leitura pública que o SITE precisa hoje é 100% coberta por
--          RPCs SECURITY DEFINER (que validam, filtram e aplicam rate limit):
--            - get_available_slots / get_occupied_slots → página de agendamento
--            - get_bookings_by_token / cancel_booking_public → gerenciar/cancelar
--            - get_bookings_by_phone_rate_limited / get_last_booking_by_phone_rate_limited
--            - get_client_dashboard → painel do cliente (/cliente)
--          Nenhuma parte pública do app faz SELECT direto na tabela bookings
--          (verificado na auditoria: 0 referências públicas).
--
--          Solução: REMOVER a policy pública. O admin continua com acesso
--          total via as policies "Agendamentos ..." da migration 007
--          (escopo por barbeiro) e a tabela deixa de ser legível por anon
--          (inclusive via Realtime).
--
--   🚨 2. O AuthGuard do frontend só verificava existência de sessão —
--          qualquer usuário autenticado (mesmo não-admin) conseguia abrir
--          as telas admin. A função is_admin() (001) é SECURITY DEFINER,
--          mas sem GRANT EXECUTE explícito alguns projetos Supabase
--          revogam o EXECUTE padrão de PUBLIC, impossibilitando o
--          frontend de validar. Aqui garantimos o GRANT para que o
--          AuthGuard possa rejeitar não-admins.
--
--  ⚠️  Ordem: rodar DEPOIS das migrations 001-007.
--      Reversão da policy: recriar
--        CREATE POLICY "Leitura publica agendamentos" ON public.bookings
--        FOR SELECT USING (
--          (status IN ('pending', 'confirmed') AND booking_date >= CURRENT_DATE)
--          OR status = 'completed'
--        );
-- =========================================================================

-- ──────────────────────────────────────────────────────────────────────
-- 1. REMOVER A POLICY PÚBLICA DE LEITURA DE BOOKINGS
-- ──────────────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Leitura publica agendamentos" ON public.bookings;

-- ──────────────────────────────────────────────────────────────────────
-- 2. GARANTIR QUE is_admin() SEJA CHAMÁVEL PELO FRONTEND AUTENTICADO
--    (usada pelo AuthGuard para validar acesso às telas admin)
-- ──────────────────────────────────────────────────────────────────────
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- ──────────────────────────────────────────────────────────────────────
-- 3. VALIDAÇÃO MANUAL (opcional — rode no SQL Editor para conferir):
--
--    SET ROLE anon;
--    SELECT count(*) FROM bookings;    -- deve falhar (permission denied)
--    SELECT * FROM get_occupied_slots(CURRENT_DATE); -- ok (RPC pública)
--    RESET ROLE;
--
--    Depois valide com: node scripts/audit-rls.mjs
-- ──────────────────────────────────────────────────────────────────────
